services:
  - type: web
    name: ai-governance-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgresql://kavach_ai_user:wLtE50W5WcVQVJLQ0yR8fABrKw956T0c@dpg-dabdsr61egvs73f2enj0-a/kavach_ai"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MONGO_URI
        value: "mongodb+srv://alokinfoproict_db_user:fzXfm0IBsudp0ZG1@cluster0.99rdhte.mongodb.net/?appName=Cluster0"